package com.imooc.util;

import static org.junit.Assert.*;

import org.junit.Test;

public class CalculatorTestAutoGenerated {

	@Test
	public void testAdd() {
		fail("Not yet implemented");
	}

	@Test
	public void testSub() {
		fail("Not yet implemented");
	}

	@Test
	public void testMul() {
		fail("Not yet implemented");
	}

	@Test
	public void testDiv() {
		fail("Not yet implemented");
	}

}
